-- =============================================================================
-- Work board history from Linear, slimmed (CORE-184; board: CORE-177, decision K3).
-- Platform schema only. Idempotent: items already on the board are skipped with
-- their events, team counters only move forward.
-- ROLLBACK (manual): DELETE FROM platform.work_item WHERE source = 'linear_import';
-- =============================================================================
-- Generated by infrastructure/scripts/work-board-import.mjs --sql from the Linear export of 2026-10-07T21:35:01.442Z.
-- 9 items, 1 kept comments. Do not edit by hand; regenerate.

INSERT INTO platform.work_team (key, name, kind) VALUES ('CORE', 'CORE', 'client') ON CONFLICT (key) DO NOTHING;

WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 179, 'Detail-view tabs: active tab underline invisible', 'On the patient card (and every detail view using DetailViewTabs from 600px up) no tab looks selected: the user can''t tell which tab they are on. Since [CORE-135](https://linear.app/neosleep/issue/CORE-135/one-apple-style-segmented-control-for-every-switcher), scoped CSS `.app-segmented-tabs__thumb { background: surface }` overrides the `bg-primary` utility (Vuetify 4 puts utilities in a cascade layer), so the underline bar is painted in the surface color and disappears.', 'AppSegmentedTabs underline variant: the thumb is explicitly primary-colored again, and the active label uses primary too so the selected tab reads at a glance. Track (calendar) variant unchanged.',
    '* Underline thumb + active label are primary in light and dark
* Unit test pins the underline thumb color rule
* Calendar segmented control looks unchanged', 'done', 0, ARRAY['Bug']::text[],
    '[{"kind":"pr","url":"https://github.com/lukasz512/NeoSleep/pull/499","title":"CORE-179 Detail-view tabs show which tab is active again"},{"kind":"artifact","url":"https://claude.ai/artifact/XWAY8QAA4CA3a2thJd7aoN","title":"Artifact: CORE-179 Active Tab Visible"}]'::jsonb, NULL, 'linear_import', 'CORE-179', 'linear',
    '2026-10-07T19:36:41.899Z'::timestamptz, '2026-10-07T19:58:41.672Z'::timestamptz, '2026-10-07T19:58:41.672Z'::timestamptz, '2026-10-07T19:58:41.672Z'::timestamptz)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'done', 'Imported from Linear CORE-179', 'linear', 'import', '2026-10-07T19:36:41.899Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 180, 'Repo security baseline: secret scanning, push protection, CodeQL, gitleaks', 'The repo is public. Secret scanning, push protection and Dependabot alerts are all switched off, and there is no CodeQL or history scan. One leaked key in git history would be readable by anyone. A med-tech product has to be able to show a scanning baseline.', '* Scan the full git history with gitleaks. If anything leaks, rotate the key before going further.
* Add `.github/workflows/security.yml`: gitleaks on every PR/push and CodeQL (JS/TS) on PR, on push to dev and weekly. Add a `.gitleaks.toml` allowlist for test fixtures.
* Turn on in repo settings: secret scanning, push protection and Dependabot alerts. Alerts only; Renovate stays the only bot that opens PRs.
* Decision source: gh-pr-r1/r2 decision forms. The repo stays public and on free GitHub.',
    '* A history scan report exists with 0 open findings.
* The security workflow is green on the PR.
* The settings API shows secret scanning, push protection and Dependabot alerts enabled.', 'done', 2, '{}'::text[],
    '[{"kind":"pr","url":"https://github.com/lukasz512/NeoSleep/pull/503","title":"CORE-180 Security baseline: gitleaks + CodeQL, E2E password out of source"},{"kind":"artifact","url":"https://claude.ai/artifact/XSKzzWcAVfV1Gn2W5j5CUe","title":"Artifact: CORE-180 Repo security baseline"}]'::jsonb, NULL, 'linear_import', 'CORE-180', 'linear',
    '2026-10-07T19:40:57.008Z'::timestamptz, '2026-10-07T20:15:19.920Z'::timestamptz, '2026-10-07T20:15:19.920Z'::timestamptz, '2026-10-07T20:15:19.920Z'::timestamptz)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'done', 'Imported from Linear CORE-180', 'linear', 'import', '2026-10-07T19:40:57.008Z'::timestamptz FROM ins
UNION ALL SELECT id, 'comment', NULL, 'Skan historii znalazł hasło konta testowego, które istnieje na produkcji (rola rep). Kod już go nie zawiera, każdy PR przechodzi gitleaks i CodeQL, a GitHub blokuje push z kluczem.
**Otwarte:** decyzja D1 o koncie e2e-auth na prod (dezaktywacja + przegląd logowań). Do tego czasu ticket zostaje In Progress.
Artifact: https://claude.ai/artifact/XSKzzWcAVfV1Gn2W5j5CUe
Linear: https://linear.app/neosleep/issue/CORE-180
VS Code: vscode://anthropic.claude-code/open?session=435b3510-f712-48e8-9c3a-bdb2f1702a6b
…', 'linear', 'import', '2026-10-07T19:56:56.976Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 181, 'Live data layer: Pinia Colada, patient card as the pattern', 'Cross-view refresh relies on hand-written window events (patient-changed, checklist-updated). Any screen nobody wired up stays stale until F5, and every visit to a view refetches behind a spinner.', 'Add Pinia Colada as the query layer: data lives under keys (`[''patient'', id]`) and a mutation invalidates those keys. Move the patient card first as the reference pattern, with optimistic save. Live push from the API (SSE) is a separate follow-up ticket (decision D3 = "more").',
    '* Saving a visit refreshes the patient list, the calendar and the patient card without F5 (e2e test).
* Returning to the patient card shows cached data immediately and revalidates in the background (test).
* A failed optimistic save rolls back and shows the error (test).
* The patient card uses no window events; a short ADR documents the pattern for the other views.

Decision: [https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG](<https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG>)', 'backlog', 2, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-181', 'linear',
    '2026-10-07T19:52:00.647Z'::timestamptz, '2026-10-07T19:52:00.647Z'::timestamptz, '2026-10-07T19:52:00.647Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'backlog', 'Imported from Linear CORE-181', 'linear', 'import', '2026-10-07T19:52:00.647Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 182, 'Story coverage report: acceptance criteria mapped to e2e tests', 'docs/stories holds 68 stories with criteria and none maps each criterion to a test. Screens look done while save/refresh/other screens don''t work, so Łukasz does the QA by hand. About 19 pwa tests assert source strings instead of behavior.', 'Tests carry `@<TICKET> ACn`. `story-coverage.mjs` maps a story''s criteria to tests and **blocks from day one** (Łukasz 2026-10-07, replaces D2''s 2-week report): pre-push, CI and the ship-artifact handover refuse a gap; a UI change also needs a real-backend e2e. Skills: criteria written as user paths, /dev feat builds the whole slice tests-first (no API stub).',
    '* The script lists every story''s covered/uncovered criteria (unit-tested); CI summary shows the table.
* A ticket branch with an untested criterion fails pre-push, CI and the handover.
* The ship-artifact page shows the ticket''s criteria → tests table.
* A follow-up ticket exists for replacing the brittle source-string tests.

Decision: [https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG](<https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG>)', 'needs_review', 3, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-182', 'linear',
    '2026-10-07T19:52:03.751Z'::timestamptz, '2026-10-07T19:52:03.751Z'::timestamptz, '2026-10-07T19:52:03.751Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'needs_review', 'Imported from Linear CORE-182', 'linear', 'import', '2026-10-07T19:52:03.751Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 183, 'linear-worker takes non-UI tickets labelled auto in the background', 'Routine tickets (backend, hooks, docs) run in Łukasz''s interactive session, which is the most expensive one: every reply re-sends the whole history, including CI waits and handover steps.', 'linear-worker picks up tickets labelled `auto` that change no UI ([change-shape.sh](<http://change-shape.sh>) = light), each in its own short session, and ends with the light handover. UI tickets stay in chat (decision D1 = "more").',
    '* A ticket labelled `auto` is picked up, pushed, commented on Linear and moved to Needs Review with no interactive session (dry-run test of the worker).
* The worker refuses (and comments why) when the diff turns out to touch .vue/.css or a view.
* The `auto` label exists in CORE and NEO, and CLAUDE_WORKFLOW.md says when to use it.

Decision: [https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG](<https://claude.ai/artifact/7d4M9s7oxnkVjbLgz6PhVG>)', 'backlog', 3, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-183', 'linear',
    '2026-10-07T19:52:07.161Z'::timestamptz, '2026-10-07T19:52:07.161Z'::timestamptz, '2026-10-07T19:52:07.161Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'backlog', 'Imported from Linear CORE-183', 'linear', 'import', '2026-10-07T19:52:07.161Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 184, 'Work board: Linear history import as a reviewed migration', 'The board ([CORE-177](https://linear.app/neosleep/issue/CORE-177/platform-kanban-in-admin-replaces-linear-v1-board)) is live on dev but empty. The import would write to the shared Supabase database (production data), and data changes there go only through a reviewed migration.', '* `work-board-import.mjs --sql <file>` generates idempotent SQL from the slimmed export (ON CONFLICT DO NOTHING, team counters bumped with GREATEST).
* Migration 060 with the snapshot of 2026-10-07: 391 tickets, 235 kept comments, and a `created` event for each.
* A test checks that the migration is idempotent and that the counters continue after the highest number.',
    '* After the merge, the pwa-dev board shows the history and CORE/NEO continue numbering after the max.
* Applying the migration a second time changes nothing.', 'done', 2, '{}'::text[],
    '[{"kind":"pr","url":"https://github.com/lukasz512/NeoSleep/pull/504","title":"CORE-184 Work board: Linear history import as a reviewed migration"},{"kind":"spec","url":"https://claude.ai/artifact/MzpAPuPSLXpL5DstY57r8T","title":"Artifact: CORE-184 Work board history"}]'::jsonb, NULL, 'linear_import', 'CORE-184', 'linear',
    '2026-10-07T20:18:21.718Z'::timestamptz, '2026-10-07T20:44:19.823Z'::timestamptz, '2026-10-07T20:44:19.823Z'::timestamptz, '2026-10-07T20:44:19.823Z'::timestamptz)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'done', 'Imported from Linear CORE-184', 'linear', 'import', '2026-10-07T20:18:21.718Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 185, 'Triage + fix CodeQL and Dependabot alerts (first scan baseline)', 'The first scan after [CORE-180](https://linear.app/neosleep/issue/CORE-180/repo-security-baseline-secret-scanning-push-protection-codeql-gitleaks) found 30 open CodeQL alerts (17 high, 13 medium) and 4 Dependabot alerts (1 critical shell-quote, 2 high source-map-js/serialize-javascript, 1 medium). Nobody knows yet which ones are real holes.', '* Go through every alert: either fix it or dismiss it as a false positive / used-in-tests with a written reason.
* Order: critical/high first (user-controlled-bypass, path-injection, remote-property-injection, tainted-format-string, incomplete-hostname-regexp), then medium.
* Dependabot: bump the transitive deps with pnpm overrides; Renovate stays the only PR bot.
* Each real fix comes with a failing test first.',
    '* 0 open critical/high alerts in the Security tab, each closed by a fix or a dismissal with a reason.
* An Artifact table lists alert → verdict → fix/test.', 'backlog', 2, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-185', 'linear',
    '2026-10-07T20:55:41.575Z'::timestamptz, '2026-10-07T20:55:41.575Z'::timestamptz, '2026-10-07T20:55:41.575Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'backlog', 'Imported from Linear CORE-185', 'linear', 'import', '2026-10-07T20:55:41.575Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 186, 'Replace pwa tests that assert source strings with behavior tests', 'About 19 pwa tests read a component''s source file and assert that a string is in it. They pass while the feature is broken and fail on harmless refactors.', 'Rewrite each one as a behavior test (mount + interact, or an e2e step against the real API), tagged with its story''s `@<TICKET> ACn` where one exists ([CORE-182](https://linear.app/neosleep/issue/CORE-182/story-coverage-report-acceptance-criteria-mapped-to-e2e-tests)). Delete the ones that test nothing.',
    '* No pwa spec reads a .vue/.ts source file to assert on its text (a repo-hygiene test enforces it).
* Every replaced test fails when the behavior it covers is broken (checked once by breaking it).', 'backlog', 0, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-186', 'linear',
    '2026-10-07T21:03:16.346Z'::timestamptz, '2026-10-07T21:03:16.346Z'::timestamptz, '2026-10-07T21:03:16.346Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'backlog', 'Imported from Linear CORE-186', 'linear', 'import', '2026-10-07T21:03:16.346Z'::timestamptz FROM ins;
WITH ins AS (
  INSERT INTO platform.work_item
    (team_key, number, title, problem, change, done_when, status, priority, labels, links, branch,
     source, linear_identifier, created_by, created_at, updated_at, status_changed_at, completed_at)
  VALUES ('CORE', 187, 'Work board becomes the one source of truth for Claude sessions (D2)', '[CORE-177](https://linear.app/neosleep/issue/CORE-177/platform-kanban-in-admin-replaces-linear-v1-board)/184 put the work board on /platform/board with full Linear history, but every Claude session still creates and moves tickets in Linear. From day one the board goes stale and Linear keeps eating the 250-issue cap.', '* A "session" actor next to human/agent: a token for Claude Code sessions that may create items, comment, add links/branch and move to Needs Review, never Done.
* `.claude/ticket-teams`, the ticket-format hook, quality-gate, ship-artifact and worktree-clean read/write the board API instead of Linear.
* Final Linear import of tickets created after 2026-10-07, then Linear goes read-only (D2).',
    '* A new Claude session creates its ticket on the board, comments the branch there and ship-artifact moves it to Needs Review on the board.
* The session token cannot move an item to Done (test).
* No hook or skill writes to Linear any more; Linear holds nothing newer than the board.', 'building', 2, '{}'::text[],
    '[]'::jsonb, NULL, 'linear_import', 'CORE-187', 'linear',
    '2026-10-07T21:03:19.474Z'::timestamptz, '2026-10-07T21:03:19.474Z'::timestamptz, '2026-10-07T21:03:19.474Z'::timestamptz, NULL)
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO platform.work_item_event (item_id, kind, to_status, body, actor, actor_kind, created_at)
SELECT id, 'created', 'building', 'Imported from Linear CORE-187', 'linear', 'import', '2026-10-07T21:03:19.474Z'::timestamptz FROM ins;

UPDATE platform.work_team t SET next_number = GREATEST(t.next_number, m.max_number + 1)
  FROM (SELECT team_key, max(number) AS max_number FROM platform.work_item GROUP BY team_key) m
 WHERE m.team_key = t.key;
