/**
 * Regenerates create_tenant_schema() from the reference tenant schema
 * ("neosleep") — the step every migration that adds or changes a tenant
 * table must also do (see 027_sync_create_tenant_schema.sql's header for why,
 * and scripts/check-tenant-schema-parity.ts, which fails CI when it's
 * skipped). 027 was generated by hand with this same technique; this script
 * makes it repeatable instead of a one-off.
 *
 * Usage — against a database that has had EVERY migration applied from
 * scratch (a throwaway postgres:15 container, like CI's — never the live
 * Supabase dev DB, which has drifted from the migration files, see 027):
 *
 *   DATABASE_URL=... pnpm --filter @neo/api exec tsx scripts/generate-create-tenant-schema.ts > /tmp/fn.sql
 *
 * then append the output to the new migration, re-run migrations from
 * scratch, and confirm with check-tenant-schema-parity.
 *
 * Output shape matches 027 exactly: pg_dump's DDL unqualified (no
 * "neosleep." / "neosleep_" prefixes — the function runs under SET LOCAL
 * search_path), tables and indexes as IF NOT EXISTS, then every constraint
 * dropped IF EXISTS (foreign keys first) and re-added (keys first), so
 * re-running the function against an existing schema stays safe.
 *
 * Fails loudly on any pg_dump statement kind it doesn't know how to
 * translate (triggers, sequences, views, ...) rather than silently leaving
 * it out of the function.
 */
import { execFileSync } from "node:child_process";

const REFERENCE_SCHEMA = "neosleep";

interface Constraint {
  table: string;
  name: string;
  statement: string;
}

function dumpStatements(databaseUrl: string): string[] {
  const dump = execFileSync(
    "pg_dump",
    [databaseUrl, "--schema-only", `--schema=${REFERENCE_SCHEMA}`, "--no-owner", "--no-privileges"],
    { encoding: "utf-8", maxBuffer: 1024 * 1024 * 64 }
  );

  const statements: string[] = [];
  let current: string[] = [];
  for (const line of dump.split("\n")) {
    if (current.length === 0 && (line.trim() === "" || line.startsWith("--") || line.startsWith("\\"))) continue;
    current.push(line);
    if (line.trimEnd().endsWith(";")) {
      statements.push(current.join("\n"));
      current = [];
    }
  }
  return statements
    .filter((s) => !/^(SET |SELECT pg_catalog\.set_config|CREATE SCHEMA )/.test(s))
    .map((s) => s.split(`${REFERENCE_SCHEMA}.`).join("").split(`${REFERENCE_SCHEMA}_`).join(""));
}

function execute(statement: string): string {
  if (statement.includes("$tenant_ddl$")) throw new Error(`statement contains the dollar-quote tag: ${statement}`);
  return `  EXECUTE $tenant_ddl$${statement}$tenant_ddl$;\n`;
}

export function generateCreateTenantSchema(statements: string[]): string {
  const tablesAndIndexes: string[] = [];
  const keys: Constraint[] = [];
  const foreignKeys: Constraint[] = [];

  for (const statement of statements) {
    if (statement.startsWith("CREATE TABLE ")) {
      tablesAndIndexes.push(statement.replace(/^CREATE TABLE /, "CREATE TABLE IF NOT EXISTS "));
      continue;
    }
    if (/^CREATE (UNIQUE )?INDEX /.test(statement)) {
      tablesAndIndexes.push(statement.replace(/^CREATE (UNIQUE )?INDEX /, "CREATE $1INDEX IF NOT EXISTS "));
      continue;
    }
    const constraint = /^ALTER TABLE ONLY (\S+)\n\s+ADD CONSTRAINT (\S+) ([\s\S]+)$/.exec(statement);
    if (constraint) {
      const [, table, name, definition] = constraint as unknown as [string, string, string, string];
      const entry = { table, name, statement: `ALTER TABLE ${table}\n    ADD CONSTRAINT ${name} ${definition}` };
      (definition.startsWith("FOREIGN KEY") ? foreignKeys : keys).push(entry);
      continue;
    }
    throw new Error(`generate-create-tenant-schema: don't know how to translate this pg_dump statement:\n${statement}`);
  }

  const drop = (c: Constraint) => execute(`ALTER TABLE ${c.table} DROP CONSTRAINT IF EXISTS ${c.name};`);
  const out: string[] = [];
  out.push(`CREATE OR REPLACE FUNCTION create_tenant_schema(slug TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN

  -- Validate slug: lowercase alphanumeric + underscores only (prevents schema injection)
  IF slug !~ '^[a-z][a-z0-9_]{1,62}$' THEN
    RAISE EXCEPTION 'Invalid tenant slug: "%". Must match ^[a-z][a-z0-9_]+$', slug;
  END IF;

  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', slug);
  -- Same convention as apps/api/src/db/tenant.ts's withTenant(): transaction-
  -- scoped, so it never leaks into whatever the caller runs afterward.
  EXECUTE format('SET LOCAL search_path TO %I, public, extensions', slug);

  -- Phase 1: tables + indexes (IF NOT EXISTS — safe to re-run as-is)
`);
  out.push(tablesAndIndexes.map(execute).join("\n"));
  out.push("\n  -- Phase 2: drop constraints (foreign keys first — nothing depends on them)\n");
  out.push(foreignKeys.map(drop).join("\n"));
  out.push("\n");
  out.push(keys.map(drop).join("\n"));
  out.push("\n  -- Phase 3: re-add constraints (keys first — foreign keys depend on them)\n");
  out.push(keys.map((c) => execute(c.statement)).join("\n"));
  out.push("\n");
  out.push(foreignKeys.map((c) => execute(c.statement)).join("\n"));
  out.push("\nEND;\n$$;\n");
  return out.join("");
}

if (process.argv[1]?.endsWith("generate-create-tenant-schema.ts")) {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl?.trim()) throw new Error("DATABASE_URL is not set");
  process.stdout.write(generateCreateTenantSchema(dumpStatements(databaseUrl)));
}
